USE [master]
GO

/****** Object:  Database [JewelOfIndia]    Script Date: 11/12/2014 14:54:06 ******/
CREATE DATABASE [JewelOfIndia] ON  PRIMARY 
( NAME = N'JewelOfIndia', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\JewelOfIndia.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'JewelOfIndia_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\JewelOfIndia_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [JewelOfIndia] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JewelOfIndia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JewelOfIndia] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JewelOfIndia] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JewelOfIndia] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JewelOfIndia] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JewelOfIndia] SET ARITHABORT OFF 
GO

ALTER DATABASE [JewelOfIndia] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JewelOfIndia] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [JewelOfIndia] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JewelOfIndia] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JewelOfIndia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JewelOfIndia] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JewelOfIndia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JewelOfIndia] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JewelOfIndia] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JewelOfIndia] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JewelOfIndia] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JewelOfIndia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JewelOfIndia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JewelOfIndia] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JewelOfIndia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JewelOfIndia] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JewelOfIndia] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JewelOfIndia] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JewelOfIndia] SET  READ_WRITE 
GO

ALTER DATABASE [JewelOfIndia] SET RECOVERY FULL 
GO

ALTER DATABASE [JewelOfIndia] SET  MULTI_USER 
GO

ALTER DATABASE [JewelOfIndia] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JewelOfIndia] SET DB_CHAINING OFF 
GO

