//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public Apartment()
        {
            this.ApartmetSales = new HashSet<ApartmetSale>();
            this.Features = new HashSet<Feature>();
            this.Visuals = new HashSet<Visual>();
        }
    
        public long Id { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> Bathroom { get; set; }
        public Nullable<int> Garage { get; set; }
        public string Description { get; set; }
        public Nullable<short> FloorLevel { get; set; }
        public string Direction { get; set; }
        public Nullable<long> TowerId { get; set; }
    
        public virtual Tower Tower { get; set; }
        public virtual ICollection<ApartmetSale> ApartmetSales { get; set; }
        public virtual ICollection<Feature> Features { get; set; }
        public virtual ICollection<Visual> Visuals { get; set; }
    }
}
