//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Apartment
    {
        public Apartment()
        {
            this.ApartmetSales = new HashSet<ApartmetSale>();
            this.Features = new HashSet<Feature>();
        }
    
        public long Id { get; set; }

        [Required(ErrorMessage = "Please select number of bedrooms")]
        public Nullable<int> BedRoom { get; set; }

        [Required(ErrorMessage = "Please select number of bathrooms")]
        public Nullable<int> Bathroom { get; set; }

        [Required(ErrorMessage = "Please select number of garage")]
        public Nullable<int> Garage { get; set; }

        [Required(ErrorMessage = "Please enter apartment description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please select Floor Level")]
        public Nullable<short> FloorLevel { get; set; }

        [Required(ErrorMessage = "Please enter Apartment direction")]
        public string Direction { get; set; }

        [Required(ErrorMessage = "Please select the Tower")]
        public Nullable<long> TowerId { get; set; }
    
        public virtual Tower Tower { get; set; }
        public virtual ICollection<ApartmetSale> ApartmetSales { get; set; }
        public virtual ICollection<Feature> Features { get; set; }
    }
}
