//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmetSale
    {
        public int Id { get; set; }
        public Nullable<long> ApartmentId { get; set; }
        public bool IsBlocked { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> BlockStartDate { get; set; }
        public Nullable<System.DateTime> BlockEndDate { get; set; }
        public Nullable<short> SalesType { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ApartmetSale ApartmetSales1 { get; set; }
        public virtual ApartmetSale ApartmetSale1 { get; set; }
        public virtual ApartmetSale ApartmetSales11 { get; set; }
        public virtual ApartmetSale ApartmetSale2 { get; set; }
        public virtual ApartmentSalesType ApartmentSalesType { get; set; }
    }
}
