//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentSalesType
    {
        public ApartmentSalesType()
        {
            this.ApartmetSales = new HashSet<ApartmetSale>();
        }
    
        public short Id { get; set; }
        public string SalesType { get; set; }
    
        public virtual ICollection<ApartmetSale> ApartmetSales { get; set; }
    }
}
