//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Location
    {
        public Location()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int Id { get; set; }

         [Required(ErrorMessage = "Please enter Location Address")]
        public string Address { get; set; }

         [Required(ErrorMessage = "Please enter Location Zipcode")]
        public string ZipCode { get; set; }

        [Required(ErrorMessage = "Please enter Location State")]
        public string state { get; set; }

        [Required(ErrorMessage = "Please enter Location Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Please enter Location Latitude")]
        public string Latitude { get; set; }

        [Required(ErrorMessage = "Please enter Location Longitude")]
        public string Longitude { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
    }
}
