//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Towers = new HashSet<Tower>();
            this.Features = new HashSet<Feature>();
            this.Visuals = new HashSet<Visual>();
        }
    
        public long Id { get; set; }
        public string Feature { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual ICollection<Tower> Towers { get; set; }
        public virtual ICollection<Feature> Features { get; set; }
        public virtual ICollection<Visual> Visuals { get; set; }
    }
}
