//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PropertyType
    {
        public PropertyType()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter Property Type")]
        public string CodeReference { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
    }
}
