//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace JewelOfIndiaBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ApartmetSales = new HashSet<ApartmetSale>();
        }

        public long Id { get; set; }
        public string UserName { get; set; }
        //[Required(ErrorMessage = "Password can not be blank")]
        //[StringLength(8, ErrorMessage = "Password should be equal or less than 8 character")]
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        [Required(ErrorMessage = "Email can not be blank")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email is not Valid")]
        public string EmailId { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public string MobileNo { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DOB { get; set; }
        public string newPassword { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public virtual UserType UserType { get; set; }
       
        public virtual ICollection<ApartmetSale> ApartmetSales { get; set; }
    }
}
